version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    # Si usas una base de datos externa, puedes agregarla aquí
    # depends_on:
    #   - db
#  db:
#    image: postgres:15
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: mydb
#    ports:
#      - "5432:5432"
